spring:
  application:
    name: user-client

grpc:
  client:
    user:
      address: static://localhost:9090
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
  server:
    enabled: false

server:
  port: 8081
